### ISSUE TITLE
Regular expression is invalid error when certificates-relation-changed

### ISSUE THREAD

**Issue by kayra1** [canonical/tls-certificates-interface#139]
This error was discovered by @gatici [here](https://github.com/canonical/self-signed-certificates-operator/issues/103). I'm linking it here because this issue is most likely in the interface.

**Comment by saltiyazan** [comment]
[Bug](https://bugs.launchpad.net/juju/+bug/2058012) in Juju.
[Fix](https://github.com/juju/juju/pull/17446) in Juju 3.4.
