### ISSUE TITLE
Documentation recommends `relation-joined` instead of `relation-created` 

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/tls-certificates-interface#144]
`relation-joined` is fired when a remote application is scaled up (i.e. fired for each remote unit that joins the relation)
`relation-created` is fired once*, when the unit first "learns" about the relation

reference:
https://juju.is/docs/sdk/relation-name-relation-joined-event
https://juju.is/docs/sdk/relation-name-relation-created-event

with that in mind, it seems like this code (which requests a new certificate) should be for `relation-created`, not `relation-joined`:
https://github.com/canonical/tls-certificates-interface/blob/f4738be2522552a6da8fa19bf53d65af6547fd0c/lib/charms/tls_certificates_interface/v3/tls_certificates.py#L151
https://github.com/canonical/tls-certificates-interface/blob/f4738be2522552a6da8fa19bf53d65af6547fd0c/lib/charms/tls_certificates_interface/v3/tls_certificates.py#L179-L193

related:
https://github.com/canonical/opensearch-operator/pull/201
https://github.com/canonical/mysql-router-k8s-operator/pull/101

**Comment by phvalguima** [comment]
Hi @gruyaume, any particular reason for us to use the joined events instead of created ones?

**Comment by gruyaume** [comment]
@phvalguima I don't remember any specific technical reason, it has been a while since we wrote these docs. @saltiyazan wrote this PR which will address this:
- #151
