### ISSUE TITLE
SSL routines::wrong version number

### ISSUE THREAD

**Issue by juditnovak** [canonical/tls-certificates-interface#178]
### Bug Description

Since having fetched v12, v13 versions of the lib, I'm coming across the following error as in subject regularly when fetching new certificates.

### To Reproduce

Requesting certificates on an LXD-hosted unit, that are to be tested for HTTPS connection via CURL

### Environment

See pipeline https://github.com/canonical/opensearch-dashboards-operator/actions/runs/8909789680/job/24469535396

### Relevant log output

```shell
subprocess.CalledProcessError: Command '['bash', '-c', 'curl  -XPOST -H "Content-Type: application/json" -H "osd-xsrf: true" -H "Accept: application/json" https://10.231.98.161:5601/auth/login -d \'{"username":"kibanaserver","password": "1NrW1i7UR1G27i6zeMCCw4bHq1mVSck6"}\' --cacert ca.pem --verbose']' returned non-zero exit status 35.
----------------------------- Captured stderr call -----------------------------
Could not create directory '/home/runner/.ssh'.
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 10.231.98.161:5601...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 10.231.98.161 (10.231.98.161) port 5601 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: ca.pem
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* (5454) (IN), , Unknown (72):
{ [5 bytes data]
* error:0A00010B:SSL routines::wrong version number

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (35) error:0A00010B:SSL routines::wrong version number
```

**Comment by saltiyazan** [comment]
Hi @juditnovak,

I have not been able to reproduce this. Everything works ad expected for me.
I deployed a machine charm on an lxd based controller and I used both self signed certs and a certificate provider to configure my charm (using tls-certificates-interface v3.13).

I have not dealt with the same error before (`curl: (35) error:0A00010B:SSL routines::wrong version number`)

But doing some research online I see this error can be sometimes misleading and there can be server issues or proxy/networking issues in the background. here some references ([1](https://github.com/curl/curl/issues/9931#issuecomment-2019572945), [2](https://github.com/openssl/openssl/discussions/22004), 
Additionally I see that the [PR](https://github.com/canonical/opensearch-dashboards-operator/pull/22) that fetches the lib doesn't have any CI failures, failures appear on PRs that build on it if I am correct.

- Is the issue persistent or intermittent?
- Are you able to reproduce it manually? if so, could you please provide the steps and the environment setup?
- I see that you are doing network related tests (I very out of context tho), have you considered that there might be network issues? looking at the Juju debug logs of the failing CI I can see lines like `unit-opensearch-2: 19:05:05 [32mDEBUG[0m unit.opensearch/2.juju-log node-lock-fallback:2: https://10.199.41.214:9200 "GET /_nodes HTTP/1.1" 503 36`, but I don't know if that is related.

**Comment by juditnovak** [comment]
Another catch. At an occurence where it didn't happen on N previous runs :-(

I'm wondering that I may be able to re-use the pipeline mentioned in my prev comment to reproduce the issue (as that one was failrly deterministic) and provide some logs.

**Comment by juditnovak** [comment]
All right.
This was a nasty one.

No, the clue wasn't the `ca.pem`.

This error is typical when attempting to access a HTTP endpint using HTTPS protocol instead. So the problem was that my charm -- despite the (healthy) `self-signed-certificates` relation still couldn't _benefit_ from the certificates that got delivered.

(The issue was particularly difficult to track down, as they only appeared on the pipelne.)

Voila: https://bugs.launchpad.net/juju/+bug/2064876

Turns out I had all the correct certificates available on the charm -- however NOT receiving a `secret-changed` event they were never actually being used (switcing the charm to have TLS configured on the application level).

Closing this issue, as the problem wasn't here :-)
