### ISSUE TITLE
Accept IPv6 address as sans_ip for generate_csr

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/tls-certificates-interface#194]
### Bug Description

tls_certificate_interface provides helper functions to generate_csr.
However the function generate_csr accepts only IPv4 Address as sans_ip list but not IPv6 address [1].

[1] https://github.com/canonical/tls-certificates-interface/blob/main/lib/charms/tls_certificates_interface/v3/tls_certificates.py#L1080

### To Reproduce

Simple unit test could be easiest way to verify this. I will come back with the unit test.

### Environment

Sunbeam currently uses tls_certificates v1.12 but the problem can be observed in v3.15

### Relevant log output

```shell
See logs from  https://bugs.launchpad.net/sunbeam-charms/+bug/2067481
```

### Additional context

Reference bug observed in sunbeam: https://bugs.launchpad.net/sunbeam-charms/+bug/2067481

**Comment by gruyaume** [comment]
Thank you @hemanthnakkina for opening this issue. How important is supporting certificates with IPv6 SAN's IP's for sunbeam?

**Comment by hemanthnakkina** [comment]
This is low priority, bug raised for future foolproof. (I will mention the priority next time when i raise new bugs)
Thank you for the quick fix.
