### ISSUE TITLE
The tls_certificates v2 should raise an exception if relation data are not valid

### ISSUE THREAD

**Issue by rgildein** [canonical/tls-certificates-interface#225]
### Bug Description

Creating a relation between a charm using tls_certificates v2 and another using v4 will cause a silent issue where certificates are not provided. Right now, there is only one warning log message, which can be easily overlooked. 

An example of such warning message can be seen in [this](https://github.com/canonical/istio-operators/actions/runs/10390201248/job/28849058141#step:8:3343) CI run, where istio-pilot is using v2 and self-signed-certificates is using v4.

I think there should be a mechanism to verify that one side of the relation is using an incompatible version, so v4 should be able to tell that other side using v2 and raise an exception. Or another solution would be that v2 throw an exception instead of warning log message.

### To Reproduce

1. git clone git@github.com:canonical/istio-operators.git
2. git checkout fcc67bf51622ab181ac5eb2575c2277112105f65
3. sudo snap install juju --channel 3.4/stable
4. sudo snap install microk8s --channel 1.30-strict/stable
5. sudo microk8s enable dns hostpath-storage rbac metallb:10.64.140.43-10.64.140.49
6. tox -e integration -- --model test-istio --keep-models

### Environment

Juju 3.4
Microk8s 1.30-strict

### Relevant log output

```shell
unit-istio-pilot-0: 08:49:16 WARNING unit.istio-pilot/0.juju-log certificates:2: Provider relation data did not pass JSON Schema validation
```

**Comment by gruyaume** [comment]
Hello @rgildein , `v2` and `v4` are compatible versions of the library meaning the TLS requirer can be v2 and the provider can be `v4` and vice versa. 

If there is an issue with such compatibility right now it's a bug. Can you provide more information as to what is inside of the relation databags?

```
snap install jhack
jhack show-relation <tls provider>:<endpoint> <tls requirer>:<endpoint>
```

Also, it's possible for this warning message to show up prior to the tls requirer and provider inserting data. I.e. when the relation data is empty or contains the generic Juju content (addresses).

**Comment by gruyaume** [comment]
@rgildein bump!

**Comment by gruyaume** [comment]
Closing because we lack enough information to solve the issue. I strongly recommend upgrading the tls library.

**Comment by rgildein** [comment]
Hi @gruyaume, sorry for late response, I had vacation and then forgot to reply.

I observed this on our CI, and you can see all information in these runs [1](https://github.com/canonical/istio-operators/actions/runs/10390201248/job/28849058141), [2](https://github.com/canonical/istio-operators/actions/runs/10402510320/job/28848736001) and [3](https://github.com/canonical/istio-operators/actions/runs/10402355820/job/28806693310), where
- TLS provider was self-signed-certificates rev 174, which was using [v4 and patch 1](https://github.com/canonical/self-signed-certificates-operator/blob/d7fbd763c72bb288bcd0e14add706141c1d1d4df/lib/charms/tls_certificates_interface/v4/tls_certificates.py) (if I'm correct)
- TLS required was [istio-pilot](https://github.com/canonical/istio-operators/blob/main/charms/istio-pilot/metadata.yaml#L96) using [v2 and patch 16](https://github.com/canonical/istio-operators/pull/520/files)

To reproduce this issue, you can follow [these tests](https://github.com/canonical/istio-operators/blob/main/tests/test_bundle_tls_provider.py) and use [rev 1127 for istio-pilot](https://github.com/canonical/istio-operators/actions/runs/10390201248/job/28849060067#step:5:28) and rev 174 for self-signed-certificates. If you need, I can deploy it locally and provide relation data here. I identified the issue only by [this line](https://github.com/canonical/istio-operators/actions/runs/10390201248/job/28849058141#step:8:3343) from logs.

I fixed this issue for istio-pilot by updating tls_certificate, but also cert_handler library.
