### ISSUE TITLE
[FEATURE] Expiry time adjustable on lower than a day granularlity

### ISSUE THREAD

**Issue by juditnovak** [canonical/tls-certificates-interface#237]
### Enhancement Proposal

This enhancement is for testing purposes.

Currently if we would like to verify TLS certificates workflows, we need to manually tweak in the code to get a fast return.

This gets even worse when aiming for automated tests.

Our charm (Opensearch) is offering multiple certificates-rotatinons related operations (seamlessly) to clients. We would really like to have a solid testing around that.

May there be a way to help us out on this...? (Like a "secret environment variable" or so...?)

Thank you.

**Comment by gruyaume** [comment]
The problem has two components:
1. The library needs to support smaller unit of times than days. This has been addressed in #240 where the validity can be set to any timedelta.
2. The TLS certificates providers need to leverage this feature and expose it via juju configuration options. We are actively working on this for self-signed certificates in this series of PR's
    - https://github.com/canonical/self-signed-certificates-operator/pull/242: Fixing issues with CA certificate renewal
    - https://github.com/canonical/self-signed-certificates-operator/pull/236: Allowing the user to set any time delta with config options: ex. `5m` or `365d`.

**Comment by gruyaume** [comment]
Closing as this was implemented in self-signed-certificates. For more information, read the charm's [configuration options descriptions](https://charmhub.io/self-signed-certificates/configurations?channel=latest/edge).
