### ISSUE TITLE
Typo in charm library broke our CI

### ISSUE THREAD

**Issue by lucabello** [canonical/tls-certificates-interface#247]
There is a small typo `compatiblity => compatibility` in the `v3.tls_certificates` library.

This broke the linter running in our CI (which runs `codespell` on all files). We're adding this file to the ignorelist, but I figured it might be quicker to just fix it here!

https://github.com/canonical/tls-certificates-interface/blob/5e1ecf09b73be7c1577e186b2743099d89e9d0ca/lib/charms/tls_certificates_interface/v3/tls_certificates.py#L2031

**Comment by gruyaume** [comment]
Thank you for reporting this issue, here's the PR to address it:
- https://github.com/canonical/tls-certificates-interface/pull/248

**Comment by gruyaume** [comment]
Fixed by #248
