### ISSUE TITLE
Ensure provided certificates match private key

### ISSUE THREAD

**Issue by gruyaume** [canonical/tls-certificates-interface#283]
### Enhancement Proposal

On the `Requirer` side of this interface, when charms request to know their assigned certificates (ex. using `get_assigned_certificates`), only certificates that match the private key should be returned. The same should be true of the `certificate_available` event. This is a security measure to ensure that bad certificates (if the tls provider gets corrupted) don't make their way into the TLS requirer workload.

**Comment by MiaAltieri** [comment]
Wow, thank you so much for this! I think this will add in extra value to the charm and even more security! 🙏
