### ISSUE TITLE
Drop the `cryptography` dep for the requirer side

### ISSUE THREAD

**Issue by sed-i** [canonical/tls-certificates-interface#44]
Currently, both the provider and the requirer sides depend on the cryptogrpahy python package. 
This results in about 20 min extra packing time for requirer charms.

However, the charm container is ubuntu based and already has openssl, so we could potentially:
- delegate requrier side crypto logic to openssl via subprocess
- import cryptography only for the provider

Not sure about entropy though:
- What kind of randomness (entropy) is [available](https://crypto.stackexchange.com/questions/12571/good-entropy-source-for-generating-openssl-keys) to freshly provisioned charm [containers](https://stackoverflow.com/questions/56077948/how-to-improve-random-number-generation-in-kubernetes-cluster-containers)?
- Does the cryptography package do anything different from openssl with respect to entropy?

**Comment by sed-i** [comment]
> what part of the build takes the most time

That would be compiling the cryptography package from source.
Charmcraft used to accept binary packages but [not anymore](https://github.com/canonical/charmcraft/pull/541).

But seems like there's a [bypass](https://github.com/canonical/charmcraft/pull/588):
```yaml
          parts:
            charm:
              charm-binary-python-packages: [cryptography]
```
If that works then we'd just need to update the docs around the requirer.

**Comment by gruyaume** [comment]
> > what part of the build takes the most time
> 
> That would be compiling the cryptography package from source. Charmcraft used to accept binary packages but [not anymore](https://github.com/canonical/charmcraft/pull/541).
> 
> But seems like there's a [bypass](https://github.com/canonical/charmcraft/pull/588):
> 
> ```yaml
>           parts:
>             charm:
>               charm-binary-python-packages: [cryptography]
> ```
> 
> If that works then we'd just need to update the docs around the requirer.

I didn't know this existed. This sounds like a reasonable approach. We'd have to:
- Test it
- Document it

**Comment by sed-i** [comment]
Building `jsonschema` is also lengthy. May want to take the binary for that one as well.

**Comment by gruyaume** [comment]
Can I close this as it is a matter of making changes in the charms that use this interface and not in the interface itself? @sed-i
