### ISSUE TITLE
Use SANs instead of CN by default

### ISSUE THREAD

**Issue by sed-i** [canonical/tls-certificates-interface#46]
The `generate_csr` util takes a mandatory `subject` but an optional `sans_dns`.
This results in certs with deprecated features.

- Chrome already dropped support for CN
- Prometheus completely rejects such certs:
```json
        "scrapePool": "prometheus",
        "scrapeUrl": "https://prometheus.local:9090/metrics",
        "globalUrl": "https://prometheus.local:9090/metrics",
        "lastError": "Get \"https://prometheus.local:9090/metrics\": x509: certificate relies on legacy Common Name field, use SANs instead",
        "lastScrape": "2023-06-12T17:08:57.945355854-04:00",
        "lastScrapeDuration": 0.002333149,
        "health": "down",
```

**Moreover, prometheus rejects the cert even if it has both CN and SANs. We should probably drop CN entirely.**

It would be handy if the lib generated SANs by default.

**Comment by gruyaume** [comment]
Are you sure that Prometheus rejects CN's? This is from their docs:
![image](https://github.com/canonical/tls-certificates-interface/assets/18486508/826c0da5-e02c-4fad-a5a6-a9b651ee62f3)

What do you mean by drop CN entirely? I haven't encountered a cert on the web that did not have a common name.

**Comment by gruyaume** [comment]
@sed-i Any comment from my last message? I was thinking of closing this.
