### ISSUE TITLE
Advertize the ca cert over relation data unconditionally

### ISSUE THREAD

**Issue by sed-i** [canonical/tls-certificates-interface#61]
Currently, to obtain the ca cert over relation data we must first submit a CSR.
Sometimes we want to form trust (via relation) without having to send a CSR: https://github.com/canonical/traefik-k8s-operator/issues/214#issuecomment-1660868997.

This could obviate:
- https://github.com/canonical/self-signed-certificates-operator/issues/21

This would help fixing:
- https://github.com/canonical/traefik-k8s-operator/issues/214

**Comment by gruyaume** [comment]
Humm this is a change of behavior in the interface in general, it's not just a matter of changing the library. With the `certificate-transfer` interface is this still necessary?

**Comment by gruyaume** [comment]
Closing as this will be done using the `certificate-transfer` interface
