### ISSUE TITLE
Add missing x509 extensions to `generate_certificate`

### ISSUE THREAD

**Issue by sed-i** [canonical/tls-certificates-interface#73]
## Problem
The certs generated by the self-signed-certificates operator work fine, but comparing them to certs from e.g. charmhub.io and 1.1.1.1 there a few x509 extensions missing:

- X509v3 Authority Key Identifier
- X509v3 Subject Key Identifier
- X509v3 Key Usage (being impl'd in #72)
- X509v3 Extended Key Usage
- X509v3 Certificate Policies
- X509v3 Basic Constraints (contains "CA:FALSE")

We may not need all of them. For example, `openssl verify -x509_strict` complains only about one of them:
```
error 85 at 0 depth lookup: Missing Authority Key Identifier
```

And `openssl s_client -showcerts` complains about:

```
depth=0 CN = 10.43.8.206, x500UniqueIdentifier = 13b9a7cd-7fe3-450d-af31-f64a1a45350d
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = 10.43.8.206, x500UniqueIdentifier = 13b9a7cd-7fe3-450d-af31-f64a1a45350d
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = 10.43.8.206, x500UniqueIdentifier = 13b9a7cd-7fe3-450d-af31-f64a1a45350d
verify return:1
DONE
```

## Context
I am using the self-signed-certificates operator to sign a bare ip for traefik.
I have the server cert issued by the operator for the bare ip, but curl-ing the ingress url fails with:

```
*   Trying 10.43.8.206:443...
* Connected to 10.43.8.206 (10.43.8.206) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self-signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

When I repeat the same but with `external_hostname` for traefik, then curl-ing `trfk.local` works fine.

I suspect this may be because some x509 extensions are missing.

**Comment by ghislainbourgeois** [comment]
According to [RFC 5280 Seciton 4.2.1.1](https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.1), the `AuthorityKeyIdentifier` field is mandatory, except when the signing certificate is itself self-signed. Since this is the case here, I would assume that it is not required.

I think this might need a bigger task of auditing against the RFC, making sure it is strictly followed in this code base.

**Comment by sed-i** [comment]
Do you mean that all intermediate CAs don't need it?
charmhub.io and 1.1.1.1 do have it, and at the bottom of any trust chain there is a self-signed cert...
